### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by GabrielBRUSA** [GabrielBRUSA/Calculadora-de-c-rgulo-trigonom-trico#1]
- [ ] Perguntar se vai inserir em RAD ou º.

- [ ] Calcular RAD se for º.

- [ ] Perguntar se vai ser seno, cosseno ou tangente.

- [ ] Fazer aproximação se o angulo/rad for maior que 90º.

- [ ] Printar o resultado
